/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RideService } from "../ride.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RideCreateInput } from "./RideCreateInput";
import { Ride } from "./Ride";
import { RideFindManyArgs } from "./RideFindManyArgs";
import { RideWhereUniqueInput } from "./RideWhereUniqueInput";
import { RideUpdateInput } from "./RideUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RideControllerBase {
  constructor(
    protected readonly service: RideService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ride })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRide(@common.Body() data: RideCreateInput): Promise<Ride> {
    return await this.service.createRide({
      data: {
        ...data,

        driver: data.driver
          ? {
              connect: data.driver,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        driver: {
          select: {
            id: true,
          },
        },

        dropOffLocation: true,
        fare: true,
        id: true,
        pickUpLocation: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Ride] })
  @ApiNestedQuery(RideFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async rides(@common.Req() request: Request): Promise<Ride[]> {
    const args = plainToClass(RideFindManyArgs, request.query);
    return this.service.rides({
      ...args,
      select: {
        createdAt: true,

        driver: {
          select: {
            id: true,
          },
        },

        dropOffLocation: true,
        fare: true,
        id: true,
        pickUpLocation: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ride })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async ride(
    @common.Param() params: RideWhereUniqueInput
  ): Promise<Ride | null> {
    const result = await this.service.ride({
      where: params,
      select: {
        createdAt: true,

        driver: {
          select: {
            id: true,
          },
        },

        dropOffLocation: true,
        fare: true,
        id: true,
        pickUpLocation: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ride })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRide(
    @common.Param() params: RideWhereUniqueInput,
    @common.Body() data: RideUpdateInput
  ): Promise<Ride | null> {
    try {
      return await this.service.updateRide({
        where: params,
        data: {
          ...data,

          driver: data.driver
            ? {
                connect: data.driver,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          driver: {
            select: {
              id: true,
            },
          },

          dropOffLocation: true,
          fare: true,
          id: true,
          pickUpLocation: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ride })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ride",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRide(
    @common.Param() params: RideWhereUniqueInput
  ): Promise<Ride | null> {
    try {
      return await this.service.deleteRide({
        where: params,
        select: {
          createdAt: true,

          driver: {
            select: {
              id: true,
            },
          },

          dropOffLocation: true,
          fare: true,
          id: true,
          pickUpLocation: true,
          status: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
